[UPDATE] Major update

diff --git a/git-templates/hooks/post-checkout b/git-templates/hooks/post-checkout
--- a/git-templates/hooks/post-checkout
+++ b/git-templates/hooks/post-checkout
@@ -1,12 +1,3 @@
-#!/usr/bin/env bash
-
-.git/hooks/ctags >/dev/null 2>&1 &
-
-if [ $1 != 0000000000000000000000000000000000000000 ]; then
-  if [ $3 = 1 -a -f Gemfile ] && command -v bundle >/dev/null &&
-    git diff --name-only $1 $2 | egrep -q '^Gemfile|\.gemspec$'
-  then
-    (unset GIT_DIR; exec bundle) | grep -v '^Using ' | grep -v ' is complete'
-    true
-  fi
-fi
+#!/bin/sh
+command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
+git lfs post-checkout "$@"
